import sys
from PyQt5 import uic
from PyQt5.QtWidgets import *

form_class = uic.loadUiType('panel.ui')[0]

ssint = {1:5,2:5,3:5,4:5,5:5,6:5,7:5,8:5,9:5,10:5,11:5,12:5,13:5,14:5,15:5,16:5,17:5,18:5,19:5,20:5,21:5,22:5,23:5,24:5,25:5}
sslist = {1:[],2:[],3:[],4:[],5:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}

# Imported from guipicker
# Returns str with 10 elements in a row
def tenslice(l):
    ret = ''
    if l:
        for i in range(max(0, len(l)//10)+1):
            t = []
            for x in l[10*i:10*(i+1)]: t.append(x)
            ret += ', '.join(str(x).rjust(2) for x in t) + '\n'
    else: ret = '없음'
    return ret

class WindowClass(QMainWindow, form_class):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Numerous radio buttons
        self.rad_01_1.clicked.connect(self.radpush)
        self.rad_01_2.clicked.connect(self.radpush)
        self.rad_01_3.clicked.connect(self.radpush)
        self.rad_01_4.clicked.connect(self.radpush)
        self.rad_01_5.clicked.connect(self.radpush)
        self.rad_02_1.clicked.connect(self.radpush)
        self.rad_02_2.clicked.connect(self.radpush)
        self.rad_02_3.clicked.connect(self.radpush)
        self.rad_02_4.clicked.connect(self.radpush)
        self.rad_02_5.clicked.connect(self.radpush)
        self.rad_03_1.clicked.connect(self.radpush)
        self.rad_03_2.clicked.connect(self.radpush)
        self.rad_03_3.clicked.connect(self.radpush)
        self.rad_03_4.clicked.connect(self.radpush)
        self.rad_03_5.clicked.connect(self.radpush)
        self.rad_04_1.clicked.connect(self.radpush)
        self.rad_04_2.clicked.connect(self.radpush)
        self.rad_04_3.clicked.connect(self.radpush)
        self.rad_04_4.clicked.connect(self.radpush)
        self.rad_04_5.clicked.connect(self.radpush)
        self.rad_05_1.clicked.connect(self.radpush)
        self.rad_05_2.clicked.connect(self.radpush)
        self.rad_05_3.clicked.connect(self.radpush)
        self.rad_05_4.clicked.connect(self.radpush)
        self.rad_05_5.clicked.connect(self.radpush)
        self.rad_06_1.clicked.connect(self.radpush)
        self.rad_06_2.clicked.connect(self.radpush)
        self.rad_06_3.clicked.connect(self.radpush)
        self.rad_06_4.clicked.connect(self.radpush)
        self.rad_06_5.clicked.connect(self.radpush)
        self.rad_07_1.clicked.connect(self.radpush)
        self.rad_07_2.clicked.connect(self.radpush)
        self.rad_07_3.clicked.connect(self.radpush)
        self.rad_07_4.clicked.connect(self.radpush)
        self.rad_07_5.clicked.connect(self.radpush)
        self.rad_08_1.clicked.connect(self.radpush)
        self.rad_08_2.clicked.connect(self.radpush)
        self.rad_08_3.clicked.connect(self.radpush)
        self.rad_08_4.clicked.connect(self.radpush)
        self.rad_08_5.clicked.connect(self.radpush)
        self.rad_09_1.clicked.connect(self.radpush)
        self.rad_09_2.clicked.connect(self.radpush)
        self.rad_09_3.clicked.connect(self.radpush)
        self.rad_09_4.clicked.connect(self.radpush)
        self.rad_09_5.clicked.connect(self.radpush)
        self.rad_10_1.clicked.connect(self.radpush)
        self.rad_10_2.clicked.connect(self.radpush)
        self.rad_10_3.clicked.connect(self.radpush)
        self.rad_10_4.clicked.connect(self.radpush)
        self.rad_10_5.clicked.connect(self.radpush)
        self.rad_11_1.clicked.connect(self.radpush)
        self.rad_11_2.clicked.connect(self.radpush)
        self.rad_11_3.clicked.connect(self.radpush)
        self.rad_11_4.clicked.connect(self.radpush)
        self.rad_11_5.clicked.connect(self.radpush)
        self.rad_12_1.clicked.connect(self.radpush)
        self.rad_12_2.clicked.connect(self.radpush)
        self.rad_12_3.clicked.connect(self.radpush)
        self.rad_12_4.clicked.connect(self.radpush)
        self.rad_12_5.clicked.connect(self.radpush)
        self.rad_13_1.clicked.connect(self.radpush)
        self.rad_13_2.clicked.connect(self.radpush)
        self.rad_13_3.clicked.connect(self.radpush)
        self.rad_13_4.clicked.connect(self.radpush)
        self.rad_13_5.clicked.connect(self.radpush)
        self.rad_14_1.clicked.connect(self.radpush)
        self.rad_14_2.clicked.connect(self.radpush)
        self.rad_14_3.clicked.connect(self.radpush)
        self.rad_14_4.clicked.connect(self.radpush)
        self.rad_14_5.clicked.connect(self.radpush)
        self.rad_15_1.clicked.connect(self.radpush)
        self.rad_15_2.clicked.connect(self.radpush)
        self.rad_15_3.clicked.connect(self.radpush)
        self.rad_15_4.clicked.connect(self.radpush)
        self.rad_15_5.clicked.connect(self.radpush)
        self.rad_16_1.clicked.connect(self.radpush)
        self.rad_16_2.clicked.connect(self.radpush)
        self.rad_16_3.clicked.connect(self.radpush)
        self.rad_16_4.clicked.connect(self.radpush)
        self.rad_16_5.clicked.connect(self.radpush)
        self.rad_17_1.clicked.connect(self.radpush)
        self.rad_17_2.clicked.connect(self.radpush)
        self.rad_17_3.clicked.connect(self.radpush)
        self.rad_17_4.clicked.connect(self.radpush)
        self.rad_17_5.clicked.connect(self.radpush)
        self.rad_18_1.clicked.connect(self.radpush)
        self.rad_18_2.clicked.connect(self.radpush)
        self.rad_18_3.clicked.connect(self.radpush)
        self.rad_18_4.clicked.connect(self.radpush)
        self.rad_18_5.clicked.connect(self.radpush)
        self.rad_19_1.clicked.connect(self.radpush)
        self.rad_19_2.clicked.connect(self.radpush)
        self.rad_19_3.clicked.connect(self.radpush)
        self.rad_19_4.clicked.connect(self.radpush)
        self.rad_19_5.clicked.connect(self.radpush)
        self.rad_20_1.clicked.connect(self.radpush)
        self.rad_20_2.clicked.connect(self.radpush)
        self.rad_20_3.clicked.connect(self.radpush)
        self.rad_20_4.clicked.connect(self.radpush)
        self.rad_20_5.clicked.connect(self.radpush)
        self.rad_21_1.clicked.connect(self.radpush)
        self.rad_21_2.clicked.connect(self.radpush)
        self.rad_21_3.clicked.connect(self.radpush)
        self.rad_21_4.clicked.connect(self.radpush)
        self.rad_21_5.clicked.connect(self.radpush)
        self.rad_22_1.clicked.connect(self.radpush)
        self.rad_22_2.clicked.connect(self.radpush)
        self.rad_22_3.clicked.connect(self.radpush)
        self.rad_22_4.clicked.connect(self.radpush)
        self.rad_22_5.clicked.connect(self.radpush)
        self.rad_23_1.clicked.connect(self.radpush)
        self.rad_23_2.clicked.connect(self.radpush)
        self.rad_23_3.clicked.connect(self.radpush)
        self.rad_23_4.clicked.connect(self.radpush)
        self.rad_23_5.clicked.connect(self.radpush)
        self.rad_24_1.clicked.connect(self.radpush)
        self.rad_24_2.clicked.connect(self.radpush)
        self.rad_24_3.clicked.connect(self.radpush)
        self.rad_24_4.clicked.connect(self.radpush)
        self.rad_24_5.clicked.connect(self.radpush)
        self.rad_25_1.clicked.connect(self.radpush)
        self.rad_25_2.clicked.connect(self.radpush)
        self.rad_25_3.clicked.connect(self.radpush)
        self.rad_25_4.clicked.connect(self.radpush)
        self.rad_25_5.clicked.connect(self.radpush)

        # Quit Button
        self.exitbtn.clicked.connect(self.qexit)

        # Student no. 9 is missing
        self.std_no_09.setHidden(True)
        self.std_name_09.setHidden(True)
        self.std_09.setHidden(True)

    # Relaying rad_clicked and statupdate
    def radpush(self):
        if self.rad_01_1.isChecked(): self.statupdate(1,1)
        elif self.rad_01_2.isChecked(): self.statupdate(1,2)
        elif self.rad_01_3.isChecked(): self.statupdate(1,3)
        elif self.rad_01_4.isChecked(): self.statupdate(1,4)
        elif self.rad_01_5.isChecked(): self.statupdate(1,5)
        if self.rad_02_1.isChecked(): self.statupdate(2,1)
        elif self.rad_02_2.isChecked(): self.statupdate(2,2)
        elif self.rad_02_3.isChecked(): self.statupdate(2,3)
        elif self.rad_02_4.isChecked(): self.statupdate(2,4)
        elif self.rad_02_5.isChecked(): self.statupdate(2,5)
        if self.rad_03_1.isChecked(): self.statupdate(3,1)
        elif self.rad_03_2.isChecked(): self.statupdate(3,2)
        elif self.rad_03_3.isChecked(): self.statupdate(3,3)
        elif self.rad_03_4.isChecked(): self.statupdate(3,4)
        elif self.rad_03_5.isChecked(): self.statupdate(3,5)
        if self.rad_04_1.isChecked(): self.statupdate(4,1)
        elif self.rad_04_2.isChecked(): self.statupdate(4,2)
        elif self.rad_04_3.isChecked(): self.statupdate(4,3)
        elif self.rad_04_4.isChecked(): self.statupdate(4,4)
        elif self.rad_04_5.isChecked(): self.statupdate(4,5)
        if self.rad_05_1.isChecked(): self.statupdate(5,1)
        elif self.rad_05_2.isChecked(): self.statupdate(5,2)
        elif self.rad_05_3.isChecked(): self.statupdate(5,3)
        elif self.rad_05_4.isChecked(): self.statupdate(5,4)
        elif self.rad_05_5.isChecked(): self.statupdate(5,5)
        if self.rad_06_1.isChecked(): self.statupdate(6,1)
        elif self.rad_06_2.isChecked(): self.statupdate(6,2)
        elif self.rad_06_3.isChecked(): self.statupdate(6,3)
        elif self.rad_06_4.isChecked(): self.statupdate(6,4)
        elif self.rad_06_5.isChecked(): self.statupdate(6,5)
        if self.rad_07_1.isChecked(): self.statupdate(7,1)
        elif self.rad_07_2.isChecked(): self.statupdate(7,2)
        elif self.rad_07_3.isChecked(): self.statupdate(7,3)
        elif self.rad_07_4.isChecked(): self.statupdate(7,4)
        elif self.rad_07_5.isChecked(): self.statupdate(7,5)
        if self.rad_08_1.isChecked(): self.statupdate(8,1)
        elif self.rad_08_2.isChecked(): self.statupdate(8,2)
        elif self.rad_08_3.isChecked(): self.statupdate(8,3)
        elif self.rad_08_4.isChecked(): self.statupdate(8,4)
        elif self.rad_08_5.isChecked(): self.statupdate(8,5)
        if self.rad_09_1.isChecked(): self.statupdate(9,1)
        elif self.rad_09_2.isChecked(): self.statupdate(9,2)
        elif self.rad_09_3.isChecked(): self.statupdate(9,3)
        elif self.rad_09_4.isChecked(): self.statupdate(9,4)
        elif self.rad_09_5.isChecked(): self.statupdate(9,5)
        if self.rad_10_1.isChecked(): self.statupdate(10,1)
        elif self.rad_10_2.isChecked(): self.statupdate(10,2)
        elif self.rad_10_3.isChecked(): self.statupdate(10,3)
        elif self.rad_10_4.isChecked(): self.statupdate(10,4)
        elif self.rad_10_5.isChecked(): self.statupdate(10,5)
        if self.rad_11_1.isChecked(): self.statupdate(11,1)
        elif self.rad_11_2.isChecked(): self.statupdate(11,2)
        elif self.rad_11_3.isChecked(): self.statupdate(11,3)
        elif self.rad_11_4.isChecked(): self.statupdate(11,4)
        elif self.rad_11_5.isChecked(): self.statupdate(11,5)
        if self.rad_12_1.isChecked(): self.statupdate(12,1)
        elif self.rad_12_2.isChecked(): self.statupdate(12,2)
        elif self.rad_12_3.isChecked(): self.statupdate(12,3)
        elif self.rad_12_4.isChecked(): self.statupdate(12,4)
        elif self.rad_12_5.isChecked(): self.statupdate(12,5)
        if self.rad_13_1.isChecked(): self.statupdate(13,1)
        elif self.rad_13_2.isChecked(): self.statupdate(13,2)
        elif self.rad_13_3.isChecked(): self.statupdate(13,3)
        elif self.rad_13_4.isChecked(): self.statupdate(13,4)
        elif self.rad_13_5.isChecked(): self.statupdate(13,5)
        if self.rad_14_1.isChecked(): self.statupdate(14,1)
        elif self.rad_14_2.isChecked(): self.statupdate(14,2)
        elif self.rad_14_3.isChecked(): self.statupdate(14,3)
        elif self.rad_14_4.isChecked(): self.statupdate(14,4)
        elif self.rad_14_5.isChecked(): self.statupdate(14,5)
        if self.rad_15_1.isChecked(): self.statupdate(15,1)
        elif self.rad_15_2.isChecked(): self.statupdate(15,2)
        elif self.rad_15_3.isChecked(): self.statupdate(15,3)
        elif self.rad_15_4.isChecked(): self.statupdate(15,4)
        elif self.rad_15_5.isChecked(): self.statupdate(15,5)
        if self.rad_16_1.isChecked(): self.statupdate(16,1)
        elif self.rad_16_2.isChecked(): self.statupdate(16,2)
        elif self.rad_16_3.isChecked(): self.statupdate(16,3)
        elif self.rad_16_4.isChecked(): self.statupdate(16,4)
        elif self.rad_16_5.isChecked(): self.statupdate(16,5)
        if self.rad_17_1.isChecked(): self.statupdate(17,1)
        elif self.rad_17_2.isChecked(): self.statupdate(17,2)
        elif self.rad_17_3.isChecked(): self.statupdate(17,3)
        elif self.rad_17_4.isChecked(): self.statupdate(17,4)
        elif self.rad_17_5.isChecked(): self.statupdate(17,5)
        if self.rad_18_1.isChecked(): self.statupdate(18,1)
        elif self.rad_18_2.isChecked(): self.statupdate(18,2)
        elif self.rad_18_3.isChecked(): self.statupdate(18,3)
        elif self.rad_18_4.isChecked(): self.statupdate(18,4)
        elif self.rad_18_5.isChecked(): self.statupdate(18,5)
        if self.rad_19_1.isChecked(): self.statupdate(19,1)
        elif self.rad_19_2.isChecked(): self.statupdate(19,2)
        elif self.rad_19_3.isChecked(): self.statupdate(19,3)
        elif self.rad_19_4.isChecked(): self.statupdate(19,4)
        elif self.rad_19_5.isChecked(): self.statupdate(19,5)
        if self.rad_20_1.isChecked(): self.statupdate(20,1)
        elif self.rad_20_2.isChecked(): self.statupdate(20,2)
        elif self.rad_20_3.isChecked(): self.statupdate(20,3)
        elif self.rad_20_4.isChecked(): self.statupdate(20,4)
        elif self.rad_20_5.isChecked(): self.statupdate(20,5)
        if self.rad_21_1.isChecked(): self.statupdate(21,1)
        elif self.rad_21_2.isChecked(): self.statupdate(21,2)
        elif self.rad_21_3.isChecked(): self.statupdate(21,3)
        elif self.rad_21_4.isChecked(): self.statupdate(21,4)
        elif self.rad_21_5.isChecked(): self.statupdate(21,5)
        if self.rad_22_1.isChecked(): self.statupdate(22,1)
        elif self.rad_22_2.isChecked(): self.statupdate(22,2)
        elif self.rad_22_3.isChecked(): self.statupdate(22,3)
        elif self.rad_22_4.isChecked(): self.statupdate(22,4)
        elif self.rad_22_5.isChecked(): self.statupdate(22,5)
        if self.rad_23_1.isChecked(): self.statupdate(23,1)
        elif self.rad_23_2.isChecked(): self.statupdate(23,2)
        elif self.rad_23_3.isChecked(): self.statupdate(23,3)
        elif self.rad_23_4.isChecked(): self.statupdate(23,4)
        elif self.rad_23_5.isChecked(): self.statupdate(23,5)
        if self.rad_24_1.isChecked(): self.statupdate(24,1)
        elif self.rad_24_2.isChecked(): self.statupdate(24,2)
        elif self.rad_24_3.isChecked(): self.statupdate(24,3)
        elif self.rad_24_4.isChecked(): self.statupdate(24,4)
        elif self.rad_24_5.isChecked(): self.statupdate(24,5)
        if self.rad_25_1.isChecked(): self.statupdate(25,1)
        elif self.rad_25_2.isChecked(): self.statupdate(25,2)
        elif self.rad_25_3.isChecked(): self.statupdate(25,3)
        elif self.rad_25_4.isChecked(): self.statupdate(25,4)
        elif self.rad_25_5.isChecked(): self.statupdate(25,5)

    # Updates students status
    def statupdate(self, stdno, option):
        global ssint, sslist
        old = ssint[stdno]; ssint[stdno] = option # Cache old option, then update dict
        sslist[old].remove(stdno); sslist[option].append(stdno) # Update list
        sslist[option].sort() # Sort to pretty-print
        self.labelupdate(old, option, 25-len(sslist[5]))

    # Updates display texts
    def labelupdate(self, old, new, remain):
        if old != 5: exec(f"self.display_content_{old}.setText(tenslice(sslist[old]))")
        if new != 5: exec(f"self.display_content_{new}.setText(tenslice(sslist[new]))")
        exec(f"self.display_total.display({remain})")

    # Custom sys.exit() function
    def qexit(self):
        print("프로그램 종료"); sys.exit()

# Run
if __name__ == '__main__':
    print("프로그램 준비 중...")
    app = QApplication(sys.argv)
    myWindow = WindowClass()
    myWindow.show()
    print("프로그램 준비 완료")
    app.exec_()
